Blog_t6_4/MvcApplication2/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcApplication2.Models
{
    public class Post
    {
        public int ID { set; get; }
        [Required]
        [StringLength(500, ErrorMessage = "Số kí trong khoảng 5->500 kí tự!", MinimumLength = 5)]
        public string Title { set; get; }
        [StringLength(2000, ErrorMessage = "Tối thiểu 10 kí tự!", MinimumLength = 10)]
        public string Body { set; get; }
        public DateTime DateCreate { set; get; }
        [DataType(DataType.DateTime, ErrorMessage = "Nhập ngày giờ!")]
        public DateTime DateUpdate { set; get; }
        public virtual ICollection<Comment> Comments { set; get; }
        public virtual ICollection<Tag> Tags { set; get; }
        public int AccountID { set; get; }
        public virtual Account account { set; get; }


        public ICollection<Comment> TiTle { get; set; }
    }
}

Blog_t6_4/MvcApplication2/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication2.Models;

namespace MvcApplication2.Controllers
{
    public class CommentController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Comment/

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Posts);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create

        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.Posts, "ID", "TiTle");
            return View();
        }

        //
        // POST: /Comment/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment,int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.PostID = idpost;
                comment.DataCreated = DateTime.Now;
             //   comment.DataUpdate = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Details/"+ idpost ,"Post");
            }

            ViewBag.PostID = new SelectList(db.Posts, "ID", "TiTle", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "TiTle", comment.PostID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "TiTle", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog_t6_4/MvcApplication2/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcApplication2.Models;

namespace MvcApplication2.Controllers
{
    public class PostController : Controller
    {
        private BlogDbContext db = new BlogDbContext();

        //
        // GET: /Post/

        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.account);
            return View(db.Posts.ToList());
        }

        //
        // GET: /Post/Details/5

        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);

            ViewData["idpost"] = id;
            
            if (post == null)
            {
                return HttpNotFound();
            }
            
            return View(post);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post)
        {
            if (ModelState.IsValid)
            {
                post.DataCreated = DateTime.Now;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Blog_t6_4/MvcApplication2/Views/Post/Create.cshtml
@model MvcApplication2.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.TiTle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TiTle)
            @Html.ValidationMessageFor(model => model.TiTle)
        </div>

        <div class="editor-label">
            @Html.TextAreaFor(model => model.BoDy)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BoDy)
            @Html.ValidationMessageFor(model => model.BoDy)
        </div>

       

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog_t6_4/MvcApplication2/Views/Post/Delete.cshtml
@model MvcApplication2.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TiTle)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TiTle)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BoDy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BoDy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DataCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DataCreated)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Blog_t6_4/MvcApplication2/Views/Post/Details.cshtml
@model MvcApplication2.Models.Post

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TiTle)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TiTle)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.BoDy)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.BoDy)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DataCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DataCreated)
    </div>
</fieldset>

@Html.Partial("_addComment", new MvcApplication2.Models.Comment(), ViewData);


<fieldset>
    <legend>Comment</legend>
    @foreach(var Comment in Model.Comments.OrderByDescending(x=>x.DataCreated).Take(5))
    {
         <div class="display-field">
       <h2>Cach day: @Html.DisplayFor(x => Comment.LastTime)
    </div>
         <div class="display-field">
        @Html.DisplayFor(x => Comment.BoDy)
    </div>
    }
</fieldset>



    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>

Blog_t6_4/MvcApplication2/Views/Post/Edit.cshtml
@model MvcApplication2.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.TiTle)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TiTle)
            @Html.ValidationMessageFor(model => model.TiTle)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BoDy)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BoDy)
            @Html.ValidationMessageFor(model => model.BoDy)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataCreated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DataCreated)
            @Html.ValidationMessageFor(model => model.DataCreated)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Blog_t6_4/MvcApplication2/Views/Post/Index.cshtml
@model IEnumerable<MvcApplication2.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TiTle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BoDy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataCreated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TiTle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BoDy)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataCreated)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

Blog_t6_4/MvcApplication2/Views/Post/_addComment.cshtml
@model MvcApplication2.Models.Comment

@using (Html.BeginForm("Create", "Comment", new { idpost=ViewData["idpost"]}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>

     
        <div class="editor-field">
            @Html.EditorFor(model => model.BoDy)
            @Html.ValidationMessageFor(model => model.BoDy)
        </div>

    

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}